/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BASICSTATION_TC_PB_H_INCLUDED
#define PB_BASICSTATION_TC_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Message type enumeration (replaces "msgtype" string field) */
typedef enum _basicstation_MsgType {
    basicstation_MsgType_MSG_UNKNOWN = 0,
    /* Station -> LNS (uplink direction) */
    basicstation_MsgType_MSG_UPDF = 1, /* Uplink data frame */
    basicstation_MsgType_MSG_JREQ = 2, /* Join request */
    basicstation_MsgType_MSG_PROPDF = 3, /* Proprietary frame */
    basicstation_MsgType_MSG_DNTXED = 4, /* TX confirmation */
    basicstation_MsgType_MSG_TIMESYNC = 5, /* Time sync request */
    /* LNS -> Station (downlink direction) */
    basicstation_MsgType_MSG_DNMSG = 10, /* Downlink message */
    basicstation_MsgType_MSG_DNSCHED = 11, /* Multicast schedule */
    basicstation_MsgType_MSG_TIMESYNC_RESP = 12, /* Time sync response */
    basicstation_MsgType_MSG_RUNCMD = 13, /* Run command */
    basicstation_MsgType_MSG_RMTSH = 14 /* Remote shell */
} basicstation_MsgType;

/* Device class enumeration */
typedef enum _basicstation_DeviceClass {
    basicstation_DeviceClass_CLASS_A = 0,
    basicstation_DeviceClass_CLASS_B = 1,
    basicstation_DeviceClass_CLASS_C = 2
} basicstation_DeviceClass;

/* Struct definitions */
/* Common radio metadata for uplink messages
 Contains all information about how the packet was received */
typedef struct _basicstation_RadioMetadata {
    /* Data rate index (0-15, region-specific) */
    uint32_t dr;
    /* Frequency in Hz */
    uint32_t freq;
    /* Radio context - opaque value passed back in downlink */
    int64_t rctx;
    /* Internal timestamp (concentrator counter, microseconds) */
    int64_t xtime;
    /* GPS time in microseconds since GPS epoch (if available)
 Set to 0 if GPS not available */
    int64_t gpstime;
    /* RSSI in dBm (typically negative, e.g., -50) */
    int32_t rssi;
    /* SNR in dB (can be negative for weak signals) */
    float snr;
    /* Fine timestamp for geolocation (-1 if not available)
 Using sint32 for efficient encoding of -1 sentinel value */
    int32_t fts;
    /* UTC receive time as Unix timestamp with fractional seconds */
    double rxtime;
} basicstation_RadioMetadata;

typedef PB_BYTES_ARRAY_T(16) basicstation_UplinkDataFrame_fopts_t;
typedef PB_BYTES_ARRAY_T(256) basicstation_UplinkDataFrame_frm_payload_t;
typedef PB_BYTES_ARRAY_T(256) basicstation_UplinkDataFrame_pdu_t;
/* Uplink data frame (msgtype: "updf")
 Sent from Station to LNS for confirmed/unconfirmed data frames */
typedef struct _basicstation_UplinkDataFrame {
    /* MAC header byte */
    uint32_t mhdr;
    /* Device address (4 bytes) */
    uint32_t dev_addr;
    /* Frame control byte */
    uint32_t fctrl;
    /* Frame counter (16-bit in LoRaWAN 1.0.x, extended by LNS) */
    uint32_t fcnt;
    /* Frame options (MAC commands in header, raw bytes) */
    basicstation_UplinkDataFrame_fopts_t fopts;
    /* Frame port (-1 if no port present, 0 for MAC commands) */
    int32_t fport;
    /* Frame payload (encrypted application data, raw bytes) */
    basicstation_UplinkDataFrame_frm_payload_t frm_payload;
    /* Message Integrity Code (4 bytes) */
    uint32_t mic;
    /* Radio metadata */
    bool has_upinfo;
    basicstation_RadioMetadata upinfo;
    /* Reference time for RX window calculation */
    double ref_time;
    /* Raw PDU (PHYPayload) - used in pdu-only mode
 When present, the parsed fields (mhdr, dev_addr, etc.) may be omitted */
    basicstation_UplinkDataFrame_pdu_t pdu;
} basicstation_UplinkDataFrame;

/* Join request (msgtype: "jreq")
 Sent from Station to LNS for OTAA join requests */
typedef struct _basicstation_JoinRequest {
    /* MAC header byte (always 0x00 for join request) */
    uint32_t mhdr;
    /* Join EUI (AppEUI in LoRaWAN 1.0.x) - 8 bytes as fixed64 */
    uint64_t join_eui;
    /* Device EUI - 8 bytes as fixed64 */
    uint64_t dev_eui;
    /* Device nonce (2 bytes in 1.0.x, extended in 1.1) */
    uint32_t dev_nonce;
    /* Message Integrity Code (4 bytes) */
    uint32_t mic;
    /* Radio metadata */
    bool has_upinfo;
    basicstation_RadioMetadata upinfo;
    /* Reference time for RX window calculation */
    double ref_time;
} basicstation_JoinRequest;

typedef PB_BYTES_ARRAY_T(256) basicstation_ProprietaryFrame_frm_payload_t;
/* Proprietary frame (msgtype: "propdf")
 Sent from Station to LNS for proprietary/vendor-specific frames */
typedef struct _basicstation_ProprietaryFrame {
    /* Entire PHYPayload as raw bytes */
    basicstation_ProprietaryFrame_frm_payload_t frm_payload;
    /* Radio metadata */
    bool has_upinfo;
    basicstation_RadioMetadata upinfo;
    /* Reference time */
    double ref_time;
} basicstation_ProprietaryFrame;

/* TX confirmation (msgtype: "dntxed")
 Sent from Station to LNS after successful downlink transmission */
typedef struct _basicstation_TxConfirmation {
    /* Downlink ID (from dnmsg) */
    int64_t diid;
    /* Device EUI */
    uint64_t dev_eui;
    /* Radio context used for TX */
    int64_t rctx;
    /* Actual transmit timestamp */
    int64_t xtime;
    /* UTC transmit time */
    double txtime;
    /* GPS time of transmission */
    int64_t gpstime;
} basicstation_TxConfirmation;

/* Time sync message (msgtype: "timesync")
 Bidirectional - Station sends request, LNS responds */
typedef struct _basicstation_TimeSync {
    /* Station -> LNS: transmission time of this message */
    double txtime;
    /* LNS -> Station: GPS time reference */
    int64_t gpstime;
    /* LNS -> Station: corresponding xtime for GPS transfer */
    int64_t xtime;
} basicstation_TimeSync;

typedef PB_BYTES_ARRAY_T(256) basicstation_DownlinkMessage_pdu_t;
/* Downlink message (msgtype: "dnmsg")
 Sent from LNS to Station for unicast downlinks */
typedef struct _basicstation_DownlinkMessage {
    /* Device EUI */
    uint64_t dev_eui;
    /* Device class */
    basicstation_DeviceClass dc;
    /* Downlink ID (for correlation with dntxed) */
    int64_t diid;
    /* PHYPayload to transmit (raw bytes, not hex) */
    basicstation_DownlinkMessage_pdu_t pdu;
    /* RX delay (seconds, typically 1) */
    uint32_t rx_delay;
    /* RX1 parameters */
    uint32_t rx1_dr;
    uint32_t rx1_freq;
    /* RX2 parameters */
    uint32_t rx2_dr;
    uint32_t rx2_freq;
    /* Priority (0 = lowest) */
    uint32_t priority;
    /* Timing reference for Class A (from uplink) */
    int64_t xtime;
    int64_t rctx;
    /* Class B/C timing */
    int64_t gpstime;
    /* Override DR/Freq for Class B/C */
    uint32_t dr;
    uint32_t freq;
    /* MuxTime for RTT monitoring */
    double mux_time;
} basicstation_DownlinkMessage;

typedef PB_BYTES_ARRAY_T(256) basicstation_ScheduleEntry_pdu_t;
/* Schedule entry for multicast */
typedef struct _basicstation_ScheduleEntry {
    /* PHYPayload */
    basicstation_ScheduleEntry_pdu_t pdu;
    /* Data rate */
    uint32_t dr;
    /* Frequency */
    uint32_t freq;
    /* Priority */
    uint32_t priority;
    /* GPS time for transmission */
    int64_t gpstime;
    /* Radio context */
    int64_t rctx;
} basicstation_ScheduleEntry;

/* Multicast schedule (msgtype: "dnsched")
 Sent from LNS to Station for Class B/C multicast */
typedef struct _basicstation_DownlinkSchedule {
    pb_size_t schedule_count;
    basicstation_ScheduleEntry schedule[16];
} basicstation_DownlinkSchedule;

/* Run command (msgtype: "runcmd")
 Sent from LNS to Station to execute a command */
typedef struct _basicstation_RunCommand {
    /* Command to execute */
    char command[256];
    /* Command arguments */
    pb_size_t arguments_count;
    char arguments[16][256];
} basicstation_RunCommand;

typedef PB_BYTES_ARRAY_T(1024) basicstation_RemoteShell_data_t;
/* Remote shell data (msgtype: "rmtsh")
 Bidirectional for remote shell session */
typedef struct _basicstation_RemoteShell {
    /* User operating the session (informational) */
    char user[64];
    /* TERM environment variable value */
    char term[32];
    /* Start session (LNS -> Station) */
    bool start;
    /* Stop session (LNS -> Station) */
    bool stop;
    /* Shell data (stdin from LNS, stdout/stderr to LNS) */
    basicstation_RemoteShell_data_t data;
} basicstation_RemoteShell;

/* Top-level wrapper message
 All TC protocol messages are wrapped in this envelope */
typedef struct _basicstation_TcMessage {
    /* Message type discriminator */
    basicstation_MsgType msg_type;
    pb_size_t which_payload;
    union {
        /* Station -> LNS */
        basicstation_UplinkDataFrame updf;
        basicstation_JoinRequest jreq;
        basicstation_ProprietaryFrame propdf;
        basicstation_TxConfirmation dntxed;
        basicstation_TimeSync timesync;
        /* LNS -> Station */
        basicstation_DownlinkMessage dnmsg;
        basicstation_DownlinkSchedule dnsched;
        basicstation_RunCommand runcmd;
        basicstation_RemoteShell rmtsh;
    } payload;
} basicstation_TcMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _basicstation_MsgType_MIN basicstation_MsgType_MSG_UNKNOWN
#define _basicstation_MsgType_MAX basicstation_MsgType_MSG_RMTSH
#define _basicstation_MsgType_ARRAYSIZE ((basicstation_MsgType)(basicstation_MsgType_MSG_RMTSH+1))

#define _basicstation_DeviceClass_MIN basicstation_DeviceClass_CLASS_A
#define _basicstation_DeviceClass_MAX basicstation_DeviceClass_CLASS_C
#define _basicstation_DeviceClass_ARRAYSIZE ((basicstation_DeviceClass)(basicstation_DeviceClass_CLASS_C+1))







#define basicstation_DownlinkMessage_dc_ENUMTYPE basicstation_DeviceClass





#define basicstation_TcMessage_msg_type_ENUMTYPE basicstation_MsgType


/* Initializer values for message structs */
#define basicstation_RadioMetadata_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define basicstation_UplinkDataFrame_init_default {0, 0, 0, 0, {0, {0}}, 0, {0, {0}}, 0, false, basicstation_RadioMetadata_init_default, 0, {0, {0}}}
#define basicstation_JoinRequest_init_default    {0, 0, 0, 0, 0, false, basicstation_RadioMetadata_init_default, 0}
#define basicstation_ProprietaryFrame_init_default {{0, {0}}, false, basicstation_RadioMetadata_init_default, 0}
#define basicstation_TxConfirmation_init_default {0, 0, 0, 0, 0, 0}
#define basicstation_TimeSync_init_default       {0, 0, 0}
#define basicstation_DownlinkMessage_init_default {0, _basicstation_DeviceClass_MIN, 0, {0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define basicstation_ScheduleEntry_init_default  {{0, {0}}, 0, 0, 0, 0, 0}
#define basicstation_DownlinkSchedule_init_default {0, {basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default, basicstation_ScheduleEntry_init_default}}
#define basicstation_RunCommand_init_default     {"", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define basicstation_RemoteShell_init_default    {"", "", 0, 0, {0, {0}}}
#define basicstation_TcMessage_init_default      {_basicstation_MsgType_MIN, 0, {basicstation_UplinkDataFrame_init_default}}
#define basicstation_RadioMetadata_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define basicstation_UplinkDataFrame_init_zero   {0, 0, 0, 0, {0, {0}}, 0, {0, {0}}, 0, false, basicstation_RadioMetadata_init_zero, 0, {0, {0}}}
#define basicstation_JoinRequest_init_zero       {0, 0, 0, 0, 0, false, basicstation_RadioMetadata_init_zero, 0}
#define basicstation_ProprietaryFrame_init_zero  {{0, {0}}, false, basicstation_RadioMetadata_init_zero, 0}
#define basicstation_TxConfirmation_init_zero    {0, 0, 0, 0, 0, 0}
#define basicstation_TimeSync_init_zero          {0, 0, 0}
#define basicstation_DownlinkMessage_init_zero   {0, _basicstation_DeviceClass_MIN, 0, {0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define basicstation_ScheduleEntry_init_zero     {{0, {0}}, 0, 0, 0, 0, 0}
#define basicstation_DownlinkSchedule_init_zero  {0, {basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero, basicstation_ScheduleEntry_init_zero}}
#define basicstation_RunCommand_init_zero        {"", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define basicstation_RemoteShell_init_zero       {"", "", 0, 0, {0, {0}}}
#define basicstation_TcMessage_init_zero         {_basicstation_MsgType_MIN, 0, {basicstation_UplinkDataFrame_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define basicstation_RadioMetadata_dr_tag        1
#define basicstation_RadioMetadata_freq_tag      2
#define basicstation_RadioMetadata_rctx_tag      3
#define basicstation_RadioMetadata_xtime_tag     4
#define basicstation_RadioMetadata_gpstime_tag   5
#define basicstation_RadioMetadata_rssi_tag      6
#define basicstation_RadioMetadata_snr_tag       7
#define basicstation_RadioMetadata_fts_tag       8
#define basicstation_RadioMetadata_rxtime_tag    9
#define basicstation_UplinkDataFrame_mhdr_tag    1
#define basicstation_UplinkDataFrame_dev_addr_tag 2
#define basicstation_UplinkDataFrame_fctrl_tag   3
#define basicstation_UplinkDataFrame_fcnt_tag    4
#define basicstation_UplinkDataFrame_fopts_tag   5
#define basicstation_UplinkDataFrame_fport_tag   6
#define basicstation_UplinkDataFrame_frm_payload_tag 7
#define basicstation_UplinkDataFrame_mic_tag     8
#define basicstation_UplinkDataFrame_upinfo_tag  9
#define basicstation_UplinkDataFrame_ref_time_tag 10
#define basicstation_UplinkDataFrame_pdu_tag     11
#define basicstation_JoinRequest_mhdr_tag        1
#define basicstation_JoinRequest_join_eui_tag    2
#define basicstation_JoinRequest_dev_eui_tag     3
#define basicstation_JoinRequest_dev_nonce_tag   4
#define basicstation_JoinRequest_mic_tag         5
#define basicstation_JoinRequest_upinfo_tag      6
#define basicstation_JoinRequest_ref_time_tag    7
#define basicstation_ProprietaryFrame_frm_payload_tag 1
#define basicstation_ProprietaryFrame_upinfo_tag 2
#define basicstation_ProprietaryFrame_ref_time_tag 3
#define basicstation_TxConfirmation_diid_tag     1
#define basicstation_TxConfirmation_dev_eui_tag  2
#define basicstation_TxConfirmation_rctx_tag     3
#define basicstation_TxConfirmation_xtime_tag    4
#define basicstation_TxConfirmation_txtime_tag   5
#define basicstation_TxConfirmation_gpstime_tag  6
#define basicstation_TimeSync_txtime_tag         1
#define basicstation_TimeSync_gpstime_tag        2
#define basicstation_TimeSync_xtime_tag          3
#define basicstation_DownlinkMessage_dev_eui_tag 1
#define basicstation_DownlinkMessage_dc_tag      2
#define basicstation_DownlinkMessage_diid_tag    3
#define basicstation_DownlinkMessage_pdu_tag     4
#define basicstation_DownlinkMessage_rx_delay_tag 5
#define basicstation_DownlinkMessage_rx1_dr_tag  6
#define basicstation_DownlinkMessage_rx1_freq_tag 7
#define basicstation_DownlinkMessage_rx2_dr_tag  8
#define basicstation_DownlinkMessage_rx2_freq_tag 9
#define basicstation_DownlinkMessage_priority_tag 10
#define basicstation_DownlinkMessage_xtime_tag   11
#define basicstation_DownlinkMessage_rctx_tag    12
#define basicstation_DownlinkMessage_gpstime_tag 13
#define basicstation_DownlinkMessage_dr_tag      14
#define basicstation_DownlinkMessage_freq_tag    15
#define basicstation_DownlinkMessage_mux_time_tag 16
#define basicstation_ScheduleEntry_pdu_tag       1
#define basicstation_ScheduleEntry_dr_tag        2
#define basicstation_ScheduleEntry_freq_tag      3
#define basicstation_ScheduleEntry_priority_tag  4
#define basicstation_ScheduleEntry_gpstime_tag   5
#define basicstation_ScheduleEntry_rctx_tag      6
#define basicstation_DownlinkSchedule_schedule_tag 1
#define basicstation_RunCommand_command_tag      1
#define basicstation_RunCommand_arguments_tag    2
#define basicstation_RemoteShell_user_tag        1
#define basicstation_RemoteShell_term_tag        2
#define basicstation_RemoteShell_start_tag       3
#define basicstation_RemoteShell_stop_tag        4
#define basicstation_RemoteShell_data_tag        5
#define basicstation_TcMessage_msg_type_tag      1
#define basicstation_TcMessage_updf_tag          2
#define basicstation_TcMessage_jreq_tag          3
#define basicstation_TcMessage_propdf_tag        4
#define basicstation_TcMessage_dntxed_tag        5
#define basicstation_TcMessage_timesync_tag      6
#define basicstation_TcMessage_dnmsg_tag         10
#define basicstation_TcMessage_dnsched_tag       11
#define basicstation_TcMessage_runcmd_tag        13
#define basicstation_TcMessage_rmtsh_tag         14

/* Struct field encoding specification for nanopb */
#define basicstation_RadioMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dr,                1) \
X(a, STATIC,   SINGULAR, UINT32,   freq,              2) \
X(a, STATIC,   SINGULAR, INT64,    rctx,              3) \
X(a, STATIC,   SINGULAR, INT64,    xtime,             4) \
X(a, STATIC,   SINGULAR, INT64,    gpstime,           5) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              6) \
X(a, STATIC,   SINGULAR, FLOAT,    snr,               7) \
X(a, STATIC,   SINGULAR, SINT32,   fts,               8) \
X(a, STATIC,   SINGULAR, DOUBLE,   rxtime,            9)
#define basicstation_RadioMetadata_CALLBACK NULL
#define basicstation_RadioMetadata_DEFAULT NULL

#define basicstation_UplinkDataFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mhdr,              1) \
X(a, STATIC,   SINGULAR, FIXED32,  dev_addr,          2) \
X(a, STATIC,   SINGULAR, UINT32,   fctrl,             3) \
X(a, STATIC,   SINGULAR, UINT32,   fcnt,              4) \
X(a, STATIC,   SINGULAR, BYTES,    fopts,             5) \
X(a, STATIC,   SINGULAR, INT32,    fport,             6) \
X(a, STATIC,   SINGULAR, BYTES,    frm_payload,       7) \
X(a, STATIC,   SINGULAR, FIXED32,  mic,               8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  upinfo,            9) \
X(a, STATIC,   SINGULAR, DOUBLE,   ref_time,         10) \
X(a, STATIC,   SINGULAR, BYTES,    pdu,              11)
#define basicstation_UplinkDataFrame_CALLBACK NULL
#define basicstation_UplinkDataFrame_DEFAULT NULL
#define basicstation_UplinkDataFrame_upinfo_MSGTYPE basicstation_RadioMetadata

#define basicstation_JoinRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mhdr,              1) \
X(a, STATIC,   SINGULAR, FIXED64,  join_eui,          2) \
X(a, STATIC,   SINGULAR, FIXED64,  dev_eui,           3) \
X(a, STATIC,   SINGULAR, UINT32,   dev_nonce,         4) \
X(a, STATIC,   SINGULAR, FIXED32,  mic,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  upinfo,            6) \
X(a, STATIC,   SINGULAR, DOUBLE,   ref_time,          7)
#define basicstation_JoinRequest_CALLBACK NULL
#define basicstation_JoinRequest_DEFAULT NULL
#define basicstation_JoinRequest_upinfo_MSGTYPE basicstation_RadioMetadata

#define basicstation_ProprietaryFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    frm_payload,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  upinfo,            2) \
X(a, STATIC,   SINGULAR, DOUBLE,   ref_time,          3)
#define basicstation_ProprietaryFrame_CALLBACK NULL
#define basicstation_ProprietaryFrame_DEFAULT NULL
#define basicstation_ProprietaryFrame_upinfo_MSGTYPE basicstation_RadioMetadata

#define basicstation_TxConfirmation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    diid,              1) \
X(a, STATIC,   SINGULAR, FIXED64,  dev_eui,           2) \
X(a, STATIC,   SINGULAR, INT64,    rctx,              3) \
X(a, STATIC,   SINGULAR, INT64,    xtime,             4) \
X(a, STATIC,   SINGULAR, DOUBLE,   txtime,            5) \
X(a, STATIC,   SINGULAR, INT64,    gpstime,           6)
#define basicstation_TxConfirmation_CALLBACK NULL
#define basicstation_TxConfirmation_DEFAULT NULL

#define basicstation_TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   txtime,            1) \
X(a, STATIC,   SINGULAR, INT64,    gpstime,           2) \
X(a, STATIC,   SINGULAR, INT64,    xtime,             3)
#define basicstation_TimeSync_CALLBACK NULL
#define basicstation_TimeSync_DEFAULT NULL

#define basicstation_DownlinkMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  dev_eui,           1) \
X(a, STATIC,   SINGULAR, UENUM,    dc,                2) \
X(a, STATIC,   SINGULAR, INT64,    diid,              3) \
X(a, STATIC,   SINGULAR, BYTES,    pdu,               4) \
X(a, STATIC,   SINGULAR, UINT32,   rx_delay,          5) \
X(a, STATIC,   SINGULAR, UINT32,   rx1_dr,            6) \
X(a, STATIC,   SINGULAR, UINT32,   rx1_freq,          7) \
X(a, STATIC,   SINGULAR, UINT32,   rx2_dr,            8) \
X(a, STATIC,   SINGULAR, UINT32,   rx2_freq,          9) \
X(a, STATIC,   SINGULAR, UINT32,   priority,         10) \
X(a, STATIC,   SINGULAR, INT64,    xtime,            11) \
X(a, STATIC,   SINGULAR, INT64,    rctx,             12) \
X(a, STATIC,   SINGULAR, INT64,    gpstime,          13) \
X(a, STATIC,   SINGULAR, UINT32,   dr,               14) \
X(a, STATIC,   SINGULAR, UINT32,   freq,             15) \
X(a, STATIC,   SINGULAR, DOUBLE,   mux_time,         16)
#define basicstation_DownlinkMessage_CALLBACK NULL
#define basicstation_DownlinkMessage_DEFAULT NULL

#define basicstation_ScheduleEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pdu,               1) \
X(a, STATIC,   SINGULAR, UINT32,   dr,                2) \
X(a, STATIC,   SINGULAR, UINT32,   freq,              3) \
X(a, STATIC,   SINGULAR, UINT32,   priority,          4) \
X(a, STATIC,   SINGULAR, INT64,    gpstime,           5) \
X(a, STATIC,   SINGULAR, INT64,    rctx,              6)
#define basicstation_ScheduleEntry_CALLBACK NULL
#define basicstation_ScheduleEntry_DEFAULT NULL

#define basicstation_DownlinkSchedule_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  schedule,          1)
#define basicstation_DownlinkSchedule_CALLBACK NULL
#define basicstation_DownlinkSchedule_DEFAULT NULL
#define basicstation_DownlinkSchedule_schedule_MSGTYPE basicstation_ScheduleEntry

#define basicstation_RunCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command,           1) \
X(a, STATIC,   REPEATED, STRING,   arguments,         2)
#define basicstation_RunCommand_CALLBACK NULL
#define basicstation_RunCommand_DEFAULT NULL

#define basicstation_RemoteShell_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   user,              1) \
X(a, STATIC,   SINGULAR, STRING,   term,              2) \
X(a, STATIC,   SINGULAR, BOOL,     start,             3) \
X(a, STATIC,   SINGULAR, BOOL,     stop,              4) \
X(a, STATIC,   SINGULAR, BYTES,    data,              5)
#define basicstation_RemoteShell_CALLBACK NULL
#define basicstation_RemoteShell_DEFAULT NULL

#define basicstation_TcMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    msg_type,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,updf,payload.updf),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,jreq,payload.jreq),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,propdf,payload.propdf),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dntxed,payload.dntxed),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,timesync,payload.timesync),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dnmsg,payload.dnmsg),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dnsched,payload.dnsched),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,runcmd,payload.runcmd),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rmtsh,payload.rmtsh),  14)
#define basicstation_TcMessage_CALLBACK NULL
#define basicstation_TcMessage_DEFAULT NULL
#define basicstation_TcMessage_payload_updf_MSGTYPE basicstation_UplinkDataFrame
#define basicstation_TcMessage_payload_jreq_MSGTYPE basicstation_JoinRequest
#define basicstation_TcMessage_payload_propdf_MSGTYPE basicstation_ProprietaryFrame
#define basicstation_TcMessage_payload_dntxed_MSGTYPE basicstation_TxConfirmation
#define basicstation_TcMessage_payload_timesync_MSGTYPE basicstation_TimeSync
#define basicstation_TcMessage_payload_dnmsg_MSGTYPE basicstation_DownlinkMessage
#define basicstation_TcMessage_payload_dnsched_MSGTYPE basicstation_DownlinkSchedule
#define basicstation_TcMessage_payload_runcmd_MSGTYPE basicstation_RunCommand
#define basicstation_TcMessage_payload_rmtsh_MSGTYPE basicstation_RemoteShell

extern const pb_msgdesc_t basicstation_RadioMetadata_msg;
extern const pb_msgdesc_t basicstation_UplinkDataFrame_msg;
extern const pb_msgdesc_t basicstation_JoinRequest_msg;
extern const pb_msgdesc_t basicstation_ProprietaryFrame_msg;
extern const pb_msgdesc_t basicstation_TxConfirmation_msg;
extern const pb_msgdesc_t basicstation_TimeSync_msg;
extern const pb_msgdesc_t basicstation_DownlinkMessage_msg;
extern const pb_msgdesc_t basicstation_ScheduleEntry_msg;
extern const pb_msgdesc_t basicstation_DownlinkSchedule_msg;
extern const pb_msgdesc_t basicstation_RunCommand_msg;
extern const pb_msgdesc_t basicstation_RemoteShell_msg;
extern const pb_msgdesc_t basicstation_TcMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define basicstation_RadioMetadata_fields &basicstation_RadioMetadata_msg
#define basicstation_UplinkDataFrame_fields &basicstation_UplinkDataFrame_msg
#define basicstation_JoinRequest_fields &basicstation_JoinRequest_msg
#define basicstation_ProprietaryFrame_fields &basicstation_ProprietaryFrame_msg
#define basicstation_TxConfirmation_fields &basicstation_TxConfirmation_msg
#define basicstation_TimeSync_fields &basicstation_TimeSync_msg
#define basicstation_DownlinkMessage_fields &basicstation_DownlinkMessage_msg
#define basicstation_ScheduleEntry_fields &basicstation_ScheduleEntry_msg
#define basicstation_DownlinkSchedule_fields &basicstation_DownlinkSchedule_msg
#define basicstation_RunCommand_fields &basicstation_RunCommand_msg
#define basicstation_RemoteShell_fields &basicstation_RemoteShell_msg
#define basicstation_TcMessage_fields &basicstation_TcMessage_msg

/* Maximum encoded size of messages (where known) */
#define BASICSTATION_TC_PB_H_MAX_SIZE            basicstation_TcMessage_size
#define basicstation_DownlinkMessage_size        372
#define basicstation_DownlinkSchedule_size       4832
#define basicstation_JoinRequest_size            122
#define basicstation_ProprietaryFrame_size       346
#define basicstation_RadioMetadata_size          76
#define basicstation_RemoteShell_size            1129
#define basicstation_RunCommand_size             4386
#define basicstation_ScheduleEntry_size          299
#define basicstation_TcMessage_size              4837
#define basicstation_TimeSync_size               31
#define basicstation_TxConfirmation_size         62
#define basicstation_UplinkDataFrame_size        662

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
