/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "tc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(basicstation_RadioMetadata, basicstation_RadioMetadata, AUTO)


PB_BIND(basicstation_UplinkDataFrame, basicstation_UplinkDataFrame, 2)


PB_BIND(basicstation_JoinRequest, basicstation_JoinRequest, AUTO)


PB_BIND(basicstation_ProprietaryFrame, basicstation_ProprietaryFrame, 2)


PB_BIND(basicstation_TxConfirmation, basicstation_TxConfirmation, AUTO)


PB_BIND(basicstation_TimeSync, basicstation_TimeSync, AUTO)


PB_BIND(basicstation_DownlinkMessage, basicstation_DownlinkMessage, 2)


PB_BIND(basicstation_ScheduleEntry, basicstation_ScheduleEntry, 2)


PB_BIND(basicstation_DownlinkSchedule, basicstation_DownlinkSchedule, 4)


PB_BIND(basicstation_RunCommand, basicstation_RunCommand, 4)


PB_BIND(basicstation_RemoteShell, basicstation_RemoteShell, 2)


PB_BIND(basicstation_TcMessage, basicstation_TcMessage, 4)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

